service: Crud

custom:
  settings:
    POSTS_TABLE: posts

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  environment: ${self:custom.settings}
  iamRoleStatements:
   - Effect: "Allow"
     Action:
        - dynamodb:DescribeTable
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
     Resource:
      - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.settings.POSTS_TABLE}"

functions:
  createPost:
    handler: Methods/createBooks.createPost
    events:
    - http:
        path: /post
        method: post
  getAllPosts:
    handler: Methods/getBooks.getAllPosts
    events:
    - http:
        path: /posts
        method: get
  getPost:
    handler: Methods/getBook.getPost
    events:
    - http:
        path: /post/{id}
        method: get
  updatePost:
    handler: Methods/updateBook.updatePost
    events:
    - http:
        path: /post/{id}
        method: put
  deletePost:
    handler: Method/deleteBook.deletePost
    events:
    - http:
        path: /post/{id}
        method: delete

resources:
  Resources:
    PostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.settings.POSTS_TABLE}