
service: serverless-s3-operations 

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  profile: default

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "s3:GetObject"
        - "s3:PutObject"
      Resource: "arn:aws:s3:::serverless-s3-operations-bucket/*"


functions:
  appendText:
    handler: handler.appendText
    events:
      - http:
          path: appendText
          method: put


resources:
  Resources:
    S3OperationsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: serverless-s3-operations-bucket